<?xml version="1.0" encoding="utf-8"?><Database Name="mTravelCredit" Class="TravelCreditDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=agni;Initial Catalog=mTravelCredit;Integrated Security=True" SettingsObjectName="DataAccess.Properties.Settings" SettingsPropertyName="mTravelCreditConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.spGetTranscationDetailsByMemberName" Method="spGetTranscationDetailsByMemberName">
    <Parameter Name="memberName" Type="System.String" DbType="NVarChar(500)" />
    <ElementType Name="spGetTranscationDetailsByMemberNameResult">
      <Column Name="TransactionId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ReferenceTransactionId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TransactionType" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ConversionFactor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UsdEquivalentAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SoftcashProgram" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Validity" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Availability" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="TransactionStatus" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="RequesterUserName" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="OrderId" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Application" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetTranscationDetailsByTimeStamp" Method="spGetTranscationDetailsByTimeStamp">
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="spGetTranscationDetailsByTimeStampResult">
      <Column Name="TransactionId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ReferenceTransactionId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TransactionType" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ConversionFactor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UsdEquivalentAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SoftcashProgram" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Validity" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Availability" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="TransactionStatus" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="RequesterUserName" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="OrderId" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Application" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spMemberExistsInMemberDetails" Method="spMemberExistsInMemberDetails">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(500)" />
    <ElementType Name="spMemberExistsInMemberDetailsResult">
      <Column Name="MemberName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MemberShips" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="MemberShipStatus" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="MemberCountry" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>