#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dTrip")]
	public partial class TripDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public TripDBDataContext() : 
				base(global::DataAccess.Properties.Settings.Default.dTripConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TripDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TripDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TripDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TripDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spGetProductDetailsByConfirmationNumber")]
		public ISingleResult<spGetProductDetailsByConfirmationNumberResult> spGetProductDetailsByConfirmationNumber([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ConfirmationNumber", DbType="NVarChar(100)")] string confirmationNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), confirmationNumber);
			return ((ISingleResult<spGetProductDetailsByConfirmationNumberResult>)(result.ReturnValue));
		}
	}
	
	public partial class spGetProductDetailsByConfirmationNumberResult
	{
		
		private string _ProductType;
		
		private int _FareSourceID;
		
		private string _FareSourceName;
		
		public spGetProductDetailsByConfirmationNumberResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductType", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string ProductType
		{
			get
			{
				return this._ProductType;
			}
			set
			{
				if ((this._ProductType != value))
				{
					this._ProductType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FareSourceID", DbType="Int NOT NULL")]
		public int FareSourceID
		{
			get
			{
				return this._FareSourceID;
			}
			set
			{
				if ((this._FareSourceID != value))
				{
					this._FareSourceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FareSourceName", DbType="NVarChar(32) NOT NULL", CanBeNull=false)]
		public string FareSourceName
		{
			get
			{
				return this._FareSourceName;
			}
			set
			{
				if ((this._FareSourceName != value))
				{
					this._FareSourceName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
